# Generated by Django 2.1b1 on 2018-06-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='create_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=20000)),
                ('lang', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
                ('expire', models.CharField(max_length=100)),
            ],
        ),
    ]
