# Generated by Django 2.1b1 on 2018-07-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_code',
            name='slug',
            field=models.CharField(max_length=20000, null=True),
        ),
    ]
