# Generated by Django 2.1b1 on 2018-07-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0002_auto_20180714_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_code',
            name='content',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
