# Generated by Django 2.1b1 on 2018-07-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0003_auto_20180714_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_code',
            name='content',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='create_code',
            name='slug',
            field=models.CharField(max_length=20000),
        ),
    ]
