# Generated by Django 2.1b1 on 2018-07-16 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0004_auto_20180714_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_code',
            name='expire',
        ),
    ]
